# Utiliza una imagen base con Java 1
FROM registry.access.redhat.com/ubi8/openjdk-17:1.16
ENV LANGUAGE='en_US:en'

COPY target/docker-discovery-service-1.0.0.jar discovery-service-1.0.0.jar

ENTRYPOINT ["java","-jar","/discovery-service-1.0.0.jar"]