version: '3'
services:
  # mongo:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: ${GIT_PWD}
  #   networks:
  #           - spring-cloud-network

  discovery-service:
    container_name: discovery-service
    build:
      context: ./../AppDiscoveryService
      dockerfile: src/docker/Dockerfile.jvm
    ports:
      - "8761:8761"
    # depends_on:
    #   - mongo
    networks:
      - spring-cloud-network

  # api-gateway:
  #   build:
  #     context: ./../AppApiGateway
  #     dockerfile: src/docker/Dockerfile.jvm
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #     - discovery-service

networks:
    spring-cloud-network:
        driver: bridge