FROM maven:3.9.4-eclipse-temurin-17 AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

FROM registry.access.redhat.com/ubi8/openjdk-17:1.16

COPY --from=builder /app/target/*.jar /app/app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]